### ISSUE TITLE
Can't save or load files on Linux

### ISSUE THREAD

**Issue by ccc814p** [richpl/PyBasic#7]
On Linux (Ubuntu), I'm trying to load a program I wrote up in a text editor. However, when I try loading it in PyBasic, it just gives me "invalid syntax". The same issue occurs when saving a PyBasic BASIC program.

**Comment by richpl** [comment]
Hi, thanks for the feedback.

Did you use a separate text editor? PyBASIC saves a program by pickling  the underlying Python object representing that program, and then unpickling it on loading. Therefore you have to create your program within the PyBASIC interpreter in order to save it. See the Readme file.

**Comment by ccc814p** [comment]
I used a seperate text editor for creating the BASIC file itself. When I loaded it with 'LOAD', and then the Linux directory, the 'invalid syntax' error occurs.

**Comment by richpl** [comment]
Like I said, you can’t load files created in another text editor because BASIC programs are saved in pickled form. I appreciate that this is slightly annoying, but it would mean quite a bit of extra development to accommodate.
